---
- name: Create containerd certs directory for docker.io
  file:
    path: /etc/containerd/certs.d/docker.io
    state: directory
    recurse: yes

- name: Copy config for docker.io mirror
  template:
    src: dockerhub-hosts.toml
    dest: /etc/containerd/certs.d/docker.io/hosts.toml
    mode: 0644

- name: Install the open-iscsi package
  # This allows us to create Longhorn volumes within a cluster
  apt:
    name: open-iscsi
    state: present
    update_cache: yes

- name: apt-clean
  apt:
    clean: yes
